### PR TITLE
Minor code edits

### PR DESCRIPTION
**Pull request by datalorax**
As the branch indicates, these are pretty minor. I think we're probably ready to announce it on twitter, if you feel ready. 

These changes:
* Renamed `check_4_cites_nih` to `.check_4_cites_nih` to be consistent with other utility functions, and moved it to the utils script.
* Fixed a minor error in the `gsub` code for description
* Removed `begin{statment}` and `end{statement}` from the skeleton.Rmd because they were just showing up in the document and didn't seem to be making any difference.
* Removed the loop on `make_numbered_citations` because `paste0` is vectorized so it wasn't needed. It's a bit faster which makes zero difference in this case but I also think it's a bit more readable.

One note, we are getting the following warning when it's knit

```
Warning message:
Package bibentry Warning: You have used \nobibliography* 
(bibentry)                without a following \bibliography.
(bibentry)                You may not be able to run BibTeX. 
```

I'm not sure if we were getting this before or how to fix it. That's the only thing I see though that makes me hesitant to say I think we can go ahead and announce it to the masses.

### CODE REVIEW

**Comment by TysonStanley** [comment]
The `\bibentry` warning was showing up on my end too. I'll look into that and get it fixed.

**Comment by TysonStanley** [comment]
The `\bibentry` warning was fixed in `master`.

**Comment by datalorax** [comment]
Wonderful! What was causing it?

**Comment by TysonStanley** [comment]
I used `\nobibliography*` in a case that wasn't necessary. Turns out I had misread the documentation but after reading it more carefully it was pretty obvious where the mistake was.

**Pull request merged**
